name: Bug Report
description: Report a problem with the Marmot client mod or developer API.
labels: [bug]
body:

  - type: markdown
    attributes:
      value: |
        ## Marmot Bug Report
        Thanks for helping improve Marmot! Please fill out all sections so we can reproduce the issue quickly.

  - type: markdown
    attributes:
      value: |
        ### ⚠️ Important - Only report issues on the *latest* Marmot version
        Bug reports for older versions will be **closed without investigation**.
        Please update to the newest release before reporting a problem.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug in detail. What did you expect to happen?
      placeholder: "When the server forces F5 third person, the camera locks incorrectly when switching back to first person."
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Which Marmot system is affected?
      description: Select all that apply.
      multiple: true
      options:
        - Custom UI Rendering (Server-side bug)
        - Custom UI Rendering (Client-side bug)
        - FOV Manipulation
        - Camera Manipulation
        - Locked F5 / Forced Perspective
        - Forced Keybinds
        - Click Tracking (begin/end events)
        - Developer API
        - Other/Unsure
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a list of actions that cause the issue.
      placeholder: |
        1. Server sends forced F5 packet
        2. Player attempts to scroll
        3. Camera resets every tick
        4. F5 becomes stuck
    validations:
      required: true

  - type: input
    id: marmot_version
    attributes:
      label: Marmot Version
      placeholder: "Example: 1.3.3"
    validations:
      required: true

  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Version
      placeholder: "Example: 1.21.10 Fabric"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Other environment information
      description: List any other mods, server type, or relevant context.
      placeholder: |
        - Fabric API 0.138.3+1.21.10
        - Sodium, Iris
        - Custom server plugin "AwesomePlugin"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / video
      description: Attach visual evidence if applicable.
      placeholder: "Drag files into this box"
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checklist
      options:
        - label: I verified this issue happens **without** other client mods.
        - label: I checked existing issues to avoid duplicates.
        - label: I included reproduction steps.
    validations:
      required: true

  - type: checkboxes
    id: version_check
    attributes:
      label: Version Requirements
      description: Marmot only accepts bug reports for the *latest released version*.
      options:
        - label: I am using the **latest** version of Marmot.
    validations:
      required: true